### ISSUE TITLE
Bundle lineage-references and outgroup 

### ISSUE THREAD

**Issue by abhi18av** [TORCH-Consortium/MAGMA#162]
Based on some recent uses of the pipeline, it was necessary to have some strains from different lineages as well as an outgroup.

I was wondering whether we should add a database similar to `EXIT-RIF` so that people can just turn on that option.

We've had some conversation over emails regarding this, boiling down to 

1. Using `-k 66` with `BWA_MEM` since older 
2. Reducing the 4 quality thresholds to push through majority of samples

**Comment by abhi18av** [comment]
Following up on the previous discussions (please feel free to add your thoughts here)


1. I used the GVCFs generated by the CALL_WF GATK Haplotype process and created a minimal GVCF for `LineageAndOutgroup` as well as `LineageAndOutgroupAndEXITRIF`. 

```
gatk CombineGVCFs --java-options "-Xmx4G" \
    -R NC-000962-3-H37Rv.fa \
     -G StandardAnnotation -G AS_StandardAnnotation  \
    --variant MTb_L9.ERR4162024.g.vcf.gz  --variant MTb_L1.SAMN10185847.g.vcf.gz  --variant MTb_L7.ERR1971849.g.vcf.gz  --variant MTb_L6.SAMEA1877150.g.vcf.gz  --variant MTb_L8.SRR10828835.g.vcf.gz  --variant MTb_L410.ERR216945.g.vcf.gz  --variant MTb_L5.SAMEA1877169.g.vcf.gz  --variant MTb_L2.SAMEA1877219.g.vcf.gz  --variant MTb_L43.ERR1193883.g.vcf.gz  --variant MTb_L3.SAMEA1877181.g.vcf.gz  \
    --variant Mcanettii.ERR5104570.g.vcf.gz \
    --variant EXIT-RIF.g.vcf.gz  \
    -O LineagesAndOutgroupsAndEXITRIF.g.vcf.gz


```



2. Then fed the GVCF file instead of any FASTQ, therefore they were incorporated in the MERGE_WF directly by skipping the filtration processes.

```yaml

use_ref_exit_rif_gvcf: true

ref_exit_rif_gvcf: /MAGMA_MTB_PROJECTS/data/exit-rif/LineagesAndOutgroups.g.vcf.gz

ref_exit_rif_gvcf_tbi: /MAGMA_MTB_PROJECTS/data/exit-rif/LineagesAndOutgroups.g.vcf.gz.tbi

```
